require("dotenv").config();
const mongoose = require("mongoose");
const Student = require("./models/Student");

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    console.log("MongoDB Connected");

    await Student.deleteMany({});

    await Student.insertMany([
     
 {
  name: "Rahul Sharma",
  rollNo: "23AIML001",
  course: "B.Tech AI & ML",
  semester: 5,
  email: "rahul.sharma@gmail.com",
  phone: "9876543210",
  cgpa: 8.74,
  result: "Pass",
  gender: "Male",
  address: "Sector 15, Hisar, Haryana"
},
{
  name: "Priya Verma",
  rollNo: "23CSE002",
  course: "B.Tech CSE",
  semester: 4,
  email: "priya.verma@gmail.com",
  phone: "9876543211",
  cgpa: 9.15,
  result: "Pass",
  gender: "Female",
  address: "Model Town, Rohtak, Haryana"
},
{
  name: "Aman Gupta",
  rollNo: "23IT003",
  course: "B.Tech IT",
  semester: 6,
  email: "aman.gupta@gmail.com",
  phone: "9876543212",
  cgpa: 7.92,
  result: "Pass",
  gender: "Male",
  address: "Rajendra Nagar, New Delhi"
},
{
  name: "Sneha Patel",
  rollNo: "23ECE004",
  course: "B.Tech ECE",
  semester: 3,
  email: "sneha.patel@gmail.com",
  phone: "9876543213",
  cgpa: 8.56,
  result: "Pass",
  gender: "Female",
  address: "Navrangpura, Ahmedabad, Gujarat"
},
{
  name: "Arjun Singh",
  rollNo: "23ME005",
  course: "B.Tech Mechanical",
  semester: 7,
  email: "arjun.singh@gmail.com",
  phone: "9876543214",
  cgpa: 6.95,
  result: "Pass",
  gender: "Male",
  address: "Civil Lines, Jaipur, Rajasthan"
},
{
  name: "Neha Yadav",
  rollNo: "23CV006",
  course: "B.Tech Civil",
  semester: 5,
  email: "neha.yadav@gmail.com",
  phone: "9876543215",
  cgpa: 9.42,
  result: "Pass",
  gender: "Female",
  address: "Gomti Nagar, Lucknow, Uttar Pradesh"
},
{
  name: "Karan Mehta",
  rollNo: "23AIML007",
  course: "B.Tech AI & ML",
  semester: 8,
  email: "karan.mehta@gmail.com",
  phone: "9876543216",
  cgpa: 7.64,
  result: "Pass",
  gender: "Male",
  address: "Vaishali Nagar, Jaipur, Rajasthan"
},
{
  name: "Ananya Sharma",
  rollNo: "23CSE008",
  course: "B.Tech CSE",
  semester: 2,
  email: "ananya.sharma@gmail.com",
  phone: "9876543217",
  cgpa: 9.67,
  result: "Pass",
  gender: "Female",
  address: "Sector 22, Chandigarh"
},
{
  name: "Rohit Kumar",
  rollNo: "23IT009",
  course: "B.Tech IT",
  semester: 4,
  email: "rohit.kumar@gmail.com",
  phone: "9876543218",
  cgpa: 5.84,
  result: "Fail",
  gender: "Male",
  address: "Kankarbagh, Patna, Bihar"
},
{
  name: "Aditi Jain",
  rollNo: "23ECE010",
  course: "B.Tech ECE",
  semester: 6,
  email: "aditi.jain@gmail.com",
  phone: "9876543219",
  cgpa: 8.88,
  result: "Pass",
  gender: "Female",
  address: "Vijay Nagar, Indore, Madhya Pradesh"
},
{
  name: "Vikram Choudhary",
  rollNo: "23ME011",
  course: "B.Tech Mechanical",
  semester: 5,
  email: "vikram.choudhary@gmail.com",
  phone: "9876543220",
  cgpa: 7.45,
  result: "Pass",
  gender: "Male",
  address: "Bikaner, Rajasthan"
},
{
  name: "Pooja Rani",
  rollNo: "23CV012",
  course: "B.Tech Civil",
  semester: 7,
  email: "pooja.rani@gmail.com",
  phone: "9876543221",
  cgpa: 8.11,
  result: "Pass",
  gender: "Female",
  address: "Panipat, Haryana"
},
{
  name: "Saurabh Mishra",
  rollNo: "23CSE013",
  course: "B.Tech CSE",
  semester: 3,
  email: "saurabh.mishra@gmail.com",
  phone: "9876543222",
  cgpa: 8.25,
  result: "Pass",
  gender: "Male",
  address: "Prayagraj, Uttar Pradesh"
},
{
  name: "Kavya Nair",
  rollNo: "23IT014",
  course: "B.Tech IT",
  semester: 2,
  email: "kavya.nair@gmail.com",
  phone: "9876543223",
  cgpa: 9.32,
  result: "Pass",
  gender: "Female",
  address: "Kochi, Kerala"
},
{
  name: "Harsh Vardhan",
  rollNo: "23ECE015",
  course: "B.Tech ECE",
  semester: 8,
  email: "harsh.vardhan@gmail.com",
  phone: "9876543224",
  cgpa: 7.18,
  result: "Pass",
  gender: "Male",
  address: "Kanpur, Uttar Pradesh"
},
{
  name: "Riya Kapoor",
  rollNo: "23AIML016",
  course: "B.Tech AI & ML",
  semester: 5,
  email: "riya.kapoor@gmail.com",
  phone: "9876543225",
  cgpa: 9.51,
  result: "Pass",
  gender: "Female",
  address: "Ludhiana, Punjab"
},
{
  name: "Deepak Yadav",
  rollNo: "23ME017",
  course: "B.Tech Mechanical",
  semester: 6,
  email: "deepak.yadav@gmail.com",
  phone: "9876543226",
  cgpa: 6.88,
  result: "Pass",
  gender: "Male",
  address: "Rewari, Haryana"
},
{
  name: "Nisha Singh",
  rollNo: "23CV018",
  course: "B.Tech Civil",
  semester: 4,
  email: "nisha.singh@gmail.com",
  phone: "9876543227",
  cgpa: 8.73,
  result: "Pass",
  gender: "Female",
  address: "Varanasi, Uttar Pradesh"
},
{
  name: "Abhishek Das",
  rollNo: "23IT019",
  course: "B.Tech IT",
  semester: 7,
  email: "abhishek.das@gmail.com",
  phone: "9876543228",
  cgpa: 7.94,
  result: "Pass",
  gender: "Male",
  address: "Bhubaneswar, Odisha"
},
{
  name: "Meera Joshi",
  rollNo: "23CSE020",
  course: "B.Tech CSE",
  semester: 1,
  email: "meera.joshi@gmail.com",
  phone: "9876543229",
  cgpa: 9.81,
  result: "Pass",
  gender: "Female",
  address: "Dehradun, Uttarakhand"
},
{
  name: "Yash Malhotra",
  rollNo: "23ECE021",
  course: "B.Tech ECE",
  semester: 5,
  email: "yash.malhotra@gmail.com",
  phone: "9876543230",
  cgpa: 7.61,
  result: "Pass",
  gender: "Male",
  address: "Gurugram, Haryana"
},
{
  name: "Simran Kaur",
  rollNo: "23AIML022",
  course: "B.Tech AI & ML",
  semester: 3,
  email: "simran.kaur@gmail.com",
  phone: "9876543231",
  cgpa: 8.93,
  result: "Pass",
  gender: "Female",
  address: "Amritsar, Punjab"
},
{
  name: "Ishita Roy",
  rollNo: "23CSE026",
  course: "B.Tech CSE",
  semester: 2,
  email: "ishita.roy@gmail.com",
  phone: "9876543235",
  cgpa: 9.22,
  result: "Pass",
  gender: "Female",
  address: "Salt Lake, Kolkata, West Bengal"
},
{
  name: "Rohan Thakur",
  rollNo: "23AIML027",
  course: "B.Tech AI & ML",
  semester: 6,
  email: "rohan.thakur@gmail.com",
  phone: "9876543236",
  cgpa: 8.14,
  result: "Pass",
  gender: "Male",
  address: "Shimla, Himachal Pradesh"
},
{
  name: "Tanvi Sharma",
  rollNo: "23IT028",
  course: "B.Tech IT",
  semester: 5,
  email: "tanvi.sharma@gmail.com",
  phone: "9876543237",
  cgpa: 8.91,
  result: "Pass",
  gender: "Female",
  address: "Noida, Uttar Pradesh"
},
{
  name: "Aditya Rao",
  rollNo: "23ECE029",
  course: "B.Tech ECE",
  semester: 7,
  email: "aditya.rao@gmail.com",
  phone: "9876543238",
  cgpa: 7.56,
  result: "Pass",
  gender: "Male",
  address: "Hyderabad, Telangana"
},
{
  name: "Muskan Arora",
  rollNo: "23ME030",
  course: "B.Tech Mechanical",
  semester: 4,
  email: "muskan.arora@gmail.com",
  phone: "9876543239",
  cgpa: 8.42,
  result: "Pass",
  gender: "Female",
  address: "Ambala, Haryana"
},
{
  name: "Naveen Kumar",
  rollNo: "23CV031",
  course: "B.Tech Civil",
  semester: 8,
  email: "naveen.kumar@gmail.com",
  phone: "9876543240",
  cgpa: 6.89,
  result: "Pass",
  gender: "Male",
  address: "Sonipat, Haryana"
},
{
  name: "Pallavi Mishra",
  rollNo: "23CSE032",
  course: "B.Tech CSE",
  semester: 3,
  email: "pallavi.mishra@gmail.com",
  phone: "9876543241",
  cgpa: 9.36,
  result: "Pass",
  gender: "Female",
  address: "Bhopal, Madhya Pradesh"
},
{
  name: "Akash Verma",
  rollNo: "23IT033",
  course: "B.Tech IT",
  semester: 1,
  email: "akash.verma@gmail.com",
  phone: "9876543242",
  cgpa: 8.05,
  result: "Pass",
  gender: "Male",
  address: "Meerut, Uttar Pradesh"
},
{
  name: "Sakshi Gupta",
  rollNo: "23ECE034",
  course: "B.Tech ECE",
  semester: 5,
  email: "sakshi.gupta@gmail.com",
  phone: "9876543243",
  cgpa: 9.11,
  result: "Pass",
  gender: "Female",
  address: "Jalandhar, Punjab"
},
{
  name: "Ritesh Singh",
  rollNo: "23AIML035",
  course: "B.Tech AI & ML",
  semester: 6,
  email: "ritesh.singh@gmail.com",
  phone: "9876543244",
  cgpa: 7.83,
  result: "Pass",
  gender: "Male",
  address: "Gaya, Bihar"
},
{
  name: "Anjali Chauhan",
  rollNo: "23ME036",
  course: "B.Tech Mechanical",
  semester: 2,
  email: "anjali.chauhan@gmail.com",
  phone: "9876543245",
  cgpa: 8.97,
  result: "Pass",
  gender: "Female",
  address: "Haridwar, Uttarakhand"
},
{
  name: "Dev Malhotra",
  rollNo: "23CV037",
  course: "B.Tech Civil",
  semester: 4,
  email: "dev.malhotra@gmail.com",
  phone: "9876543246",
  cgpa: 7.28,
  result: "Pass",
  gender: "Male",
  address: "Karnal, Haryana"
},
{
  name: "Ruchi Agarwal",
  rollNo: "23CSE038",
  course: "B.Tech CSE",
  semester: 7,
  email: "ruchi.agarwal@gmail.com",
  phone: "9876543247",
  cgpa: 9.44,
  result: "Pass",
  gender: "Female",
  address: "Agra, Uttar Pradesh"
},
{
  name: "Gaurav Saini",
  rollNo: "23IT039",
  course: "B.Tech IT",
  semester: 5,
  email: "gaurav.saini@gmail.com",
  phone: "9876543248",
  cgpa: 7.75,
  result: "Pass",
  gender: "Male",
  address: "Hisar, Haryana"
},
{
  name: "Khushi Jain",
  rollNo: "23ECE040",
  course: "B.Tech ECE",
  semester: 3,
  email: "khushi.jain@gmail.com",
  phone: "9876543249",
  cgpa: 9.58,
  result: "Pass",
  gender: "Female",
  address: "Udaipur, Rajasthan"
},
{
  name: "Manish Rawat",
  rollNo: "23AIML041",
  course: "B.Tech AI & ML",
  semester: 8,
  email: "manish.rawat@gmail.com",
  phone: "9876543250",
  cgpa: 6.91,
  result: "Pass",
  gender: "Male",
  address: "Dehradun, Uttarakhand"
},
{
  name: "Bhavna Kapoor",
  rollNo: "23ME042",
  course: "B.Tech Mechanical",
  semester: 6,
  email: "bhavna.kapoor@gmail.com",
  phone: "9876543251",
  cgpa: 8.36,
  result: "Pass",
  gender: "Female",
  address: "Ludhiana, Punjab"
},
{
  name: "Suraj Pandey",
  rollNo: "23CV043",
  course: "B.Tech Civil",
  semester: 4,
  email: "suraj.pandey@gmail.com",
  phone: "9876543252",
  cgpa: 7.62,
  result: "Pass",
  gender: "Male",
  address: "Ranchi, Jharkhand"
},
{
  name: "Nandini Rao",
  rollNo: "23CSE044",
  course: "B.Tech CSE",
  semester: 5,
  email: "nandini.rao@gmail.com",
  phone: "9876543253",
  cgpa: 9.18,
  result: "Pass",
  gender: "Female",
  address: "Mysuru, Karnataka"
},
{
  name: "Kunal Joshi",
  rollNo: "23IT045",
  course: "B.Tech IT",
  semester: 7,
  email: "kunal.joshi@gmail.com",
  phone: "9876543254",
  cgpa: 7.44,
  result: "Pass",
  gender: "Male",
  address: "Nashik, Maharashtra"
},
{
  name: "Aarohi Bhatia",
  rollNo: "23ECE046",
  course: "B.Tech ECE",
  semester: 2,
  email: "aarohi.bhatia@gmail.com",
  phone: "9876543255",
  cgpa: 9.63,
  result: "Pass",
  gender: "Female",
  address: "Chandigarh"
},
{
  name: "Shivam Dubey",
  rollNo: "23AIML047",
  course: "B.Tech AI & ML",
  semester: 3,
  email: "shivam.dubey@gmail.com",
  phone: "9876543256",
  cgpa: 8.24,
  result: "Pass",
  gender: "Male",
  address: "Jabalpur, Madhya Pradesh"
},
{
  name: "Payal Saxena",
  rollNo: "23ME048",
  course: "B.Tech Mechanical",
  semester: 1,
  email: "payal.saxena@gmail.com",
  phone: "9876543257",
  cgpa: 9.27,
  result: "Pass",
  gender: "Female",
  address: "Bareilly, Uttar Pradesh"
},
{
  name: "Vivek Tiwari",
  rollNo: "23CV049",
  course: "B.Tech Civil",
  semester: 8,
  email: "vivek.tiwari@gmail.com",
  phone: "9876543258",
  cgpa: 6.73,
  result: "Pass",
  gender: "Male",
  address: "Raipur, Chhattisgarh"
},
{
  name: "Ritika Sood",
  rollNo: "23CSE050",
  course: "B.Tech CSE",
  semester: 6,
  email: "ritika.sood@gmail.com",
  phone: "9876543259",
  cgpa: 8.84,
  result: "Pass",
  gender: "Female",
  address: "Mohali, Punjab"
},
{
  name: "Ayush Saxena",
  rollNo: "23IT051",
  course: "B.Tech IT",
  semester: 5,
  email: "ayush.saxena@gmail.com",
  phone: "9876543260",
  cgpa: 8.35,
  result: "Pass",
  gender: "Male",
  address: "Aligarh, Uttar Pradesh"
},
{
  name: "Divya Khanna",
  rollNo: "23ECE052",
  course: "B.Tech ECE",
  semester: 4,
  email: "divya.khanna@gmail.com",
  phone: "9876543261",
  cgpa: 9.08,
  result: "Pass",
  gender: "Female",
  address: "Patiala, Punjab"
},
{
  name: "Rajat Bansal",
  rollNo: "23AIML053",
  course: "B.Tech AI & ML",
  semester: 7,
  email: "rajat.bansal@gmail.com",
  phone: "9876543262",
  cgpa: 7.91,
  result: "Pass",
  gender: "Male",
  address: "Hisar, Haryana"
},
{
  name: "Komal Arora",
  rollNo: "23CSE054",
  course: "B.Tech CSE",
  semester: 2,
  email: "komal.arora@gmail.com",
  phone: "9876543263",
  cgpa: 9.47,
  result: "Pass",
  gender: "Female",
  address: "Kurukshetra, Haryana"
},
{
  name: "Sachin Yadav",
  rollNo: "23ME055",
  course: "B.Tech Mechanical",
  semester: 6,
  email: "sachin.yadav@gmail.com",
  phone: "9876543264",
  cgpa: 7.32,
  result: "Pass",
  gender: "Male",
  address: "Rewari, Haryana"
},
{
  name: "Preeti Sharma",
  rollNo: "23CV056",
  course: "B.Tech Civil",
  semester: 3,
  email: "preeti.sharma@gmail.com",
  phone: "9876543265",
  cgpa: 8.88,
  result: "Pass",
  gender: "Female",
  address: "Jaipur, Rajasthan"
},
{
  name: "Hemant Verma",
  rollNo: "23IT057",
  course: "B.Tech IT",
  semester: 8,
  email: "hemant.verma@gmail.com",
  phone: "9876543266",
  cgpa: 6.84,
  result: "Pass",
  gender: "Male",
  address: "Ghaziabad, Uttar Pradesh"
},
{
  name: "Riya Mehta",
  rollNo: "23ECE058",
  course: "B.Tech ECE",
  semester: 5,
  email: "riya.mehta@gmail.com",
  phone: "9876543267",
  cgpa: 9.52,
  result: "Pass",
  gender: "Female",
  address: "Ahmedabad, Gujarat"
},
{
  name: "Ankit Sharma",
  rollNo: "23AIML059",
  course: "B.Tech AI & ML",
  semester: 4,
  email: "ankit.sharma@gmail.com",
  phone: "9876543268",
  cgpa: 8.13,
  result: "Pass",
  gender: "Male",
  address: "Faridabad, Haryana"
},
{
  name: "Neha Kapoor",
  rollNo: "23CSE060",
  course: "B.Tech CSE",
  semester: 1,
  email: "neha.kapoor@gmail.com",
  phone: "9876543269",
  cgpa: 9.71,
  result: "Pass",
  gender: "Female",
  address: "Chandigarh"
},
{
  name: "Lokesh Kumar",
  rollNo: "23ME061",
  course: "B.Tech Mechanical",
  semester: 7,
  email: "lokesh.kumar@gmail.com",
  phone: "9876543270",
  cgpa: 7.24,
  result: "Pass",
  gender: "Male",
  address: "Rohtak, Haryana"
},
{
  name: "Ayesha Khan",
  rollNo: "23CV062",
  course: "B.Tech Civil",
  semester: 6,
  email: "ayesha.khan@gmail.com",
  phone: "9876543271",
  cgpa: 8.97,
  result: "Pass",
  gender: "Female",
  address: "Bhopal, Madhya Pradesh"
},
{
  name: "Harshit Garg",
  rollNo: "23IT063",
  course: "B.Tech IT",
  semester: 3,
  email: "harshit.garg@gmail.com",
  phone: "9876543272",
  cgpa: 8.41,
  result: "Pass",
  gender: "Male",
  address: "Sirsa, Haryana"
},
{
  name: "Sanya Malhotra",
  rollNo: "23ECE064",
  course: "B.Tech ECE",
  semester: 5,
  email: "sanya.malhotra@gmail.com",
  phone: "9876543273",
  cgpa: 9.34,
  result: "Pass",
  gender: "Female",
  address: "Noida, Uttar Pradesh"
},
{
  name: "Abhinav Jain",
  rollNo: "23AIML065",
  course: "B.Tech AI & ML",
  semester: 8,
  email: "abhinav.jain@gmail.com",
  phone: "9876543274",
  cgpa: 7.78,
  result: "Pass",
  gender: "Male",
  address: "Indore, Madhya Pradesh"
},
{
  name: "Tanisha Arora",
  rollNo: "23CSE066",
  course: "B.Tech CSE",
  semester: 4,
  email: "tanisha.arora@gmail.com",
  phone: "9876543275",
  cgpa: 8.94,
  result: "Pass",
  gender: "Female",
  address: "Delhi"
},
{
  name: "Nikhil Saini",
  rollNo: "23ME067",
  course: "B.Tech Mechanical",
  semester: 6,
  email: "nikhil.saini@gmail.com",
  phone: "9876543276",
  cgpa: 7.53,
  result: "Pass",
  gender: "Male",
  address: "Panipat, Haryana"
},
{
  name: "Pallak Gupta",
  rollNo: "23CV068",
  course: "B.Tech Civil",
  semester: 2,
  email: "pallak.gupta@gmail.com",
  phone: "9876543277",
  cgpa: 9.29,
  result: "Pass",
  gender: "Female",
  address: "Lucknow, Uttar Pradesh"
},
{
  name: "Adarsh Mishra",
  rollNo: "23IT069",
  course: "B.Tech IT",
  semester: 5,
  email: "adarsh.mishra@gmail.com",
  phone: "9876543278",
  cgpa: 8.07,
  result: "Pass",
  gender: "Male",
  address: "Prayagraj, Uttar Pradesh"
},
{
  name: "Isha Bhatia",
  rollNo: "23ECE070",
  course: "B.Tech ECE",
  semester: 3,
  email: "isha.bhatia@gmail.com",
  phone: "9876543279",
  cgpa: 9.46,
  result: "Pass",
  gender: "Female",
  address: "Ludhiana, Punjab"
},
{
  name: "Varun Sharma",
  rollNo: "23AIML071",
  course: "B.Tech AI & ML",
  semester: 7,
  email: "varun.sharma@gmail.com",
  phone: "9876543280",
  cgpa: 7.69,
  result: "Pass",
  gender: "Male",
  address: "Karnal, Haryana"
},
{
  name: "Ruchi Sood",
  rollNo: "23CSE072",
  course: "B.Tech CSE",
  semester: 1,
  email: "ruchi.sood@gmail.com",
  phone: "9876543281",
  cgpa: 9.75,
  result: "Pass",
  gender: "Female",
  address: "Mohali, Punjab"
},
{
  name: "Deepanshu Yadav",
  rollNo: "23ME073",
  course: "B.Tech Mechanical",
  semester: 8,
  email: "deepanshu.yadav@gmail.com",
  phone: "9876543282",
  cgpa: 6.92,
  result: "Pass",
  gender: "Male",
  address: "Jhajjar, Haryana"
},
{
  name: "Mansi Verma",
  rollNo: "23CV074",
  course: "B.Tech Civil",
  semester: 4,
  email: "mansi.verma@gmail.com",
  phone: "9876543283",
  cgpa: 8.82,
  result: "Pass",
  gender: "Female",
  address: "Kanpur, Uttar Pradesh"
},
{
  name: "Rohit Arora",
  rollNo: "23IT075",
  course: "B.Tech IT",
  semester: 6,
  email: "rohit.arora@gmail.com",
  phone: "9876543284",
  cgpa: 7.96,
  result: "Pass",
  gender: "Male",
  address: "Gurugram, Haryana"
},
{
  name: "Vrinda Angira",
  rollNo: "23AIML101",
  course: "B.Tech AI & ML",
  semester: 5,
  email: "vrinda.angira@gmail.com",
  phone: "9876543285",
  cgpa: 8.96,
  result: "Pass",
  gender: "Female",
  address: "Delhi"
},
{
  name: "Mafi Jangra",
  rollNo: "23CSE102",
  course: "B.Tech CSE",
  semester: 5,
  email: "mafi.jangra@gmail.com",
  phone: "9876543286",
  cgpa: 8.42,
  result: "Pass",
  gender: "Female",
  address: "Kaithal, Haryana"
},
{
  name: "Sanjana Mudhai",
  rollNo: "23IT103",
  course: "B.Tech IT",
  semester: 5,
  email: "sanjana.mudhai@gmail.com",
  phone: "9876543287",
  cgpa: 9.14,
  result: "Pass",
  gender: "Female",
  address: "Hisar, Haryana"
},
{
  name: "Yashika Kaushik",
  rollNo: "23ECE104",
  course: "B.Tech ECE",
  semester: 5,
  email: "yashika.kaushik@gmail.com",
  phone: "9876543288",
  cgpa: 8.71,
  result: "Pass",
  gender: "Female",
  address: "Meham, Haryana"
},
{
  name: "Anamika Ranga",
  rollNo: "23CV105",
  course: "B.Tech Civil",
  semester: 5,
  email: "anamika.ranga@gmail.com",
  phone: "9876543289",
  cgpa: 8.83,
  result: "Pass",
  gender: "Female",
  address: "Chandana, Kaithal, Haryana"
},
{
  name: "Komal Chahal",
  rollNo: "23ME106",
  course: "B.Tech Mechanical",
  semester: 5,
  email: "komal.chahal@gmail.com",
  phone: "9876543290",
  cgpa: 8.37,
  result: "Pass",
  gender: "Female",
  address: "Hisar, Haryana"
},
{
  name: "Sakshi Malhotra",
  rollNo: "23ECE076",
  course: "B.Tech ECE",
  semester: 3,
  email: "sakshi.malhotra@gmail.com",
  phone: "9876543285",
  cgpa: 9.13,
  result: "Pass",
  gender: "Female",
  address: "Chandigarh"
},
{
  name: "Aakash Chauhan",
  rollNo: "23AIML077",
  course: "B.Tech AI & ML",
  semester: 5,
  email: "aakash.chauhan@gmail.com",
  phone: "9876543286",
  cgpa: 8.26,
  result: "Pass",
  gender: "Male",
  address: "Meerut, Uttar Pradesh"
},
{
  name: "Nidhi Kapoor",
  rollNo: "23CSE078",
  course: "B.Tech CSE",
  semester: 2,
  email: "nidhi.kapoor@gmail.com",
  phone: "9876543287",
  cgpa: 9.61,
  result: "Pass",
  gender: "Female",
  address: "Patiala, Punjab"
},
{
  name: "Mayank Sharma",
  rollNo: "23ME079",
  course: "B.Tech Mechanical",
  semester: 6,
  email: "mayank.sharma@gmail.com",
  phone: "9876543288",
  cgpa: 7.41,
  result: "Pass",
  gender: "Male",
  address: "Hisar, Haryana"
},
{
  name: "Anjali Gupta",
  rollNo: "23CV080",
  course: "B.Tech Civil",
  semester: 4,
  email: "anjali.gupta@gmail.com",
  phone: "9876543289",
  cgpa: 8.89,
  result: "Pass",
  gender: "Female",
  address: "Jaipur, Rajasthan"
},
{
  name: "Vikas Kumar",
  rollNo: "23IT081",
  course: "B.Tech IT",
  semester: 7,
  email: "vikas.kumar@gmail.com",
  phone: "9876543290",
  cgpa: 7.75,
  result: "Pass",
  gender: "Male",
  address: "Rohtak, Haryana"
},
{
  name: "Shivani Jain",
  rollNo: "23ECE082",
  course: "B.Tech ECE",
  semester: 5,
  email: "shivani.jain@gmail.com",
  phone: "9876543291",
  cgpa: 9.29,
  result: "Pass",
  gender: "Female",
  address: "Indore, Madhya Pradesh"
},
{
  name: "Harsh Gupta",
  rollNo: "23AIML083",
  course: "B.Tech AI & ML",
  semester: 8,
  email: "harsh.gupta@gmail.com",
  phone: "9876543292",
  cgpa: 7.54,
  result: "Pass",
  gender: "Male",
  address: "Delhi"
},
{
  name: "Mehak Arora",
  rollNo: "23CSE084",
  course: "B.Tech CSE",
  semester: 1,
  email: "mehak.arora@gmail.com",
  phone: "9876543293",
  cgpa: 9.83,
  result: "Pass",
  gender: "Female",
  address: "Mohali, Punjab"
},
{
  name: "Sumit Yadav",
  rollNo: "23ME085",
  course: "B.Tech Mechanical",
  semester: 5,
  email: "sumit.yadav@gmail.com",
  phone: "9876543294",
  cgpa: 7.23,
  result: "Pass",
  gender: "Male",
  address: "Rewari, Haryana"
},
{
  name: "Poonam Verma",
  rollNo: "23CV086",
  course: "B.Tech Civil",
  semester: 6,
  email: "poonam.verma@gmail.com",
  phone: "9876543295",
  cgpa: 8.91,
  result: "Pass",
  gender: "Female",
  address: "Lucknow, Uttar Pradesh"
},
{
  name: "Aditya Bansal",
  rollNo: "23IT087",
  course: "B.Tech IT",
  semester: 4,
  email: "aditya.bansal@gmail.com",
  phone: "9876543296",
  cgpa: 8.14,
  result: "Pass",
  gender: "Male",
  address: "Faridabad, Haryana"
},
{
  name: "Khushi Sharma",
  rollNo: "23ECE088",
  course: "B.Tech ECE",
  semester: 2,
  email: "khushi.sharma@gmail.com",
  phone: "9876543297",
  cgpa: 9.58,
  result: "Pass",
  gender: "Female",
  address: "Dehradun, Uttarakhand"
},
{
  name: "Rajat Singh",
  rollNo: "23AIML089",
  course: "B.Tech AI & ML",
  semester: 7,
  email: "rajat.singh@gmail.com",
  phone: "9876543298",
  cgpa: 7.88,
  result: "Pass",
  gender: "Male",
  address: "Prayagraj, Uttar Pradesh"
},
{
  name: "Ankita Mishra",
  rollNo: "23CSE090",
  course: "B.Tech CSE",
  semester: 3,
  email: "ankita.mishra@gmail.com",
  phone: "9876543299",
  cgpa: 9.36,
  result: "Pass",
  gender: "Female",
  address: "Varanasi, Uttar Pradesh"
},
{
  name: "Deepak Arora",
  rollNo: "23ME091",
  course: "B.Tech Mechanical",
  semester: 8,
  email: "deepak.arora@gmail.com",
  phone: "9876543300",
  cgpa: 6.95,
  result: "Pass",
  gender: "Male",
  address: "Panipat, Haryana"
},
{
  name: "Ritika Sharma",
  rollNo: "23CV092",
  course: "B.Tech Civil",
  semester: 5,
  email: "ritika.sharma@gmail.com",
  phone: "9876543301",
  cgpa: 8.75,
  result: "Pass",
  gender: "Female",
  address: "Agra, Uttar Pradesh"
},
{
  name: "Yash Verma",
  rollNo: "23IT093",
  course: "B.Tech IT",
  semester: 6,
  email: "yash.verma@gmail.com",
  phone: "9876543302",
  cgpa: 8.02,
  result: "Pass",
  gender: "Male",
  address: "Noida, Uttar Pradesh"
},
{
  name: "Simran Gupta",
  rollNo: "23ECE094",
  course: "B.Tech ECE",
  semester: 4,
  email: "simran.gupta@gmail.com",
  phone: "9876543303",
  cgpa: 9.42,
  result: "Pass",
  gender: "Female",
  address: "Amritsar, Punjab"
},
{
  name: "Manoj Kumar",
  rollNo: "23AIML095",
  course: "B.Tech AI & ML",
  semester: 7,
  email: "manoj.kumar@gmail.com",
  phone: "9876543304",
  cgpa: 7.37,
  result: "Pass",
  gender: "Male",
  address: "Sonipat, Haryana"
},
{
  name: "Pallavi Saini",
  rollNo: "23CSE096",
  course: "B.Tech CSE",
  semester: 2,
  email: "pallavi.saini@gmail.com",
  phone: "9876543305",
  cgpa: 9.64,
  result: "Pass",
  gender: "Female",
  address: "Kurukshetra, Haryana"
},
{
  name: "Anurag Tiwari",
  rollNo: "23ME097",
  course: "B.Tech Mechanical",
  semester: 5,
  email: "anurag.tiwari@gmail.com",
  phone: "9876543306",
  cgpa: 7.69,
  result: "Pass",
  gender: "Male",
  address: "Kanpur, Uttar Pradesh"
},
{
  name: "Muskan Verma",
  rollNo: "23CV098",
  course: "B.Tech Civil",
  semester: 3,
  email: "muskan.verma@gmail.com",
  phone: "9876543307",
  cgpa: 8.98,
  result: "Pass",
  gender: "Female",
  address: "Jodhpur, Rajasthan"
},
{
  name: "Kartik Sharma",
  rollNo: "23IT099",
  course: "B.Tech IT",
  semester: 8,
  email: "kartik.sharma@gmail.com",
  phone: "9876543308",
  cgpa: 7.57,
  result: "Pass",
  gender: "Male",
  address: "Gurugram, Haryana"
},
{
  name: "Aditi Kapoor",
  rollNo: "23ECE100",
  course: "B.Tech ECE",
  semester: 6,
  email: "aditi.kapoor@gmail.com",
  phone: "9876543309",
  cgpa: 9.24,
  result: "Pass",
  gender: "Female",
  address: "Pune, Maharashtra"
},
{
  name: "Nitin Arora",
  rollNo: "23ME023",
  course: "B.Tech Mechanical",
  semester: 8,
  email: "nitin.arora@gmail.com",
  phone: "9876543232",
  cgpa: 6.72,
  result: "Pass",
  gender: "Male",
  address: "Faridabad, Haryana"
},
{
  name: "Shreya Kulkarni",
  rollNo: "23CV024",
  course: "B.Tech Civil",
  semester: 6,
  email: "shreya.kulkarni@gmail.com",
  phone: "9876543233",
  cgpa: 9.06,
  result: "Pass",
  gender: "Female",
  address: "Pune, Maharashtra"
},
{
  name: "Mohit Bansal",
  rollNo: "23IT025",
  course: "B.Tech IT",
  semester: 4,
  email: "mohit.bansal@gmail.com",
  phone: "9876543234",
  cgpa: 7.49,
  result: "Pass",
  gender: "Male",
  address: "Hisar, Haryana"
}
     
    ]);

    console.log("222 Students Inserted Successfully!");
    process.exit();
  })
  .catch((err) => {
    console.log(err);
    process.exit(1);
  });